### ISSUE TITLE
Cannot build as README.md file

### ISSUE THREAD

**Issue by Lastorder-DC** [OpenRCT2/title-sequence-editor#1]
`README.md` suggests running below commands.

```bash
npm install
npm run build
```
but it will fail due to missing type definitions.

According to ci.yml, @types folder should moved outside of node_modules before running `npm install`

```bash
mv node_modules/@types .
npm install
mv @types node_modules
npm run build
```

**Comment by IntelOrca** [comment]
I am hoping to get openrct2.d.ts merged into DefinitelyTyped at some point to resolve this.
